{
  "services": [
    {
      "type": "web",
      "name": "application-tracker",
      "env": "python",
      "buildCommand": "./build.sh",
      "startCommand": "cd backend && gunicorn app:app",
      "envVars": [
        {
          "key": "PYTHON_VERSION",
          "value": "3.9.0"
        }
      ],
      "disk": {
        "name": "data",
        "mountPath": "/var/data",
        "sizeGB": 1
      }
    }
  ]
}